### ISSUE TITLE
Empty array in Parquet sink causes crash

### ISSUE THREAD

**Issue by zolting** [streamingfast/substreams-sink-files#11]
## Description
When writing to a parquet file, the sink crashes with a nil pointer dereference if a message contains an `Array` type field (protobuf `repeated`) with an empty array.

## Reproduction Steps
1. Define a protobuf message with a repeated field:
```protobuf
message Example {
  repeated string examples = 1;
}
```

2. Attempt to output with an empty array:
```rust
Ok(Example {
  examples: vec![]  // This triggers the crash
})
```

3. The sink will crash with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x104012940]
```

## Stack Trace
```
goroutine 41 [running]:
github.com/parquet-go/parquet-go.(*writerColumn).flush(0x14000de1900)
	/Users/zolting/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/writer.go:1206 +0x30
github.com/parquet-go/parquet-go.(*writer).writeRowGroup(0x14000dc6160, 0x14000c1ecc0, {0x0, 0x0, 0x0})
	/Users/zolting/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/writer.go:843 +0x170
github.com/zolting/parquet-go.(*Writer).WriteRowGroup(0x14000dce140, {0x1049140e0, 0x14000460e00})
	/Users/zolting/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/writer.go:431 +0x2b0
```

## Workaround

As a temporary workaround, you can initialize the array with an empty string instead of leaving it empty:

```rust
Ok(Example {
  examples: vec![String::new()]  // This works
})
```

**Comment by maoueh** [comment]
Please try again, should be fixed now
